name: Test

on: [push, pull_request]

env:
  COVER: true

jobs:
  full-check:
    runs-on: ubuntu-latest

    # We want to run on external PRs, but not on our own internal PRs as they'll be run on push event
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != 'Cado-Labs/otel-active-support-subscriber'

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.1
          bundler-cache: true
      - name: Run Linter
        run: bundle exec rubocop
      - name: Run specs
        run: bundle exec rspec
      - name: Audit
        run: bundle exec bundle-audit
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
  specs:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}

    env:
      COVER: false

    # We want to run on external PRs, but not on our own internal PRs as they'll be run on push event
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != 'Cado-Labs/otel-active-support-subscriber'

    strategy:
      fail-fast: false
      matrix:
        ruby: [2.7, 3.0, 3.1, 3.2]
        experimental: [false]

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run specs
        run: bundle exec rspec
